### ISSUE TITLE
Some questions about VAR training

### ISSUE THREAD

**Issue by Foxerity** [daixiangzi/VAR-CLIP#1]
Hello, I was amazed to see the incredible results you've achieved with the VAR model. I sincerely want to ask you about some training details because I'm trying to train the base model (16, 256*256) for category-specific generation on the official website. 
However, after switching datasets to tiny-imagenet(200 classes, 100000 images), my training results were bad. This has left me quite puzzled, so I'm looking forward to any insights you might share, such as which default parameters might need adjustment during training or any other important training tips you think are crucial.

Thank you so much for your help!

Here are my results using all default parameters with 200 epochs. The final converged loss and accuracy are:
Lm: 6.082 Lt: 5.355
Acc m&t: 4.92 7.55

![Screenshot from 2024-07-22 00-46-37](https://github.com/user-attachments/assets/08b304bf-142f-402c-8081-a6f12bbacf59)

**Comment by daixiangzi** [comment]
I think your specific data is not enough,because official  var train 200 epoch 1k classes on 120w images, 1.2k images/per class,but you 500 images/per class, you can try train more than 200 epoch

**Comment by Foxerity** [comment]
I'm glad to receive your response. I'd like to confirm that even using the default parameters set by the original author can yield a relatively good result.

**Comment by daixiangzi** [comment]
> I'm glad to receive your response. I'd like to confirm that even using the default parameters set by the original author can yield a relatively good result.

yes, i only use default parameters but use 500 epoch on Text condition train

**Comment by daixiangzi** [comment]
> I'm glad to receive your response. I'd like to confirm that even using the default parameters set by the original author can yield a relatively good result.

I just now update class condition train log on ImageNet .you can check it

**Comment by GooThinker** [comment]
> > I'm glad to receive your response. I'd like to confirm that even using the default parameters set by the original author can yield a relatively good result.
> 
> I just now update class condition train log on ImageNet .you can check it

Thanks for your training log. But I'm curious, did you train with 16 A100s for 5 days? That's too long.T_T
