### ISSUE TITLE
The train error：not a git repository

### ISSUE THREAD

**Issue by GiftNovice** [daixiangzi/VAR-CLIP#13]
subprocess.CalledProcessError: Command 'git symbolic-ref --short HEAD 2>/dev/null || git rev-parse HEAD' returned non-zero exit status 128.
fatal: not a git repository (or any of the parent directories): .git

What does this git repository do and why does it report errors?  Thanks for answering！

**Comment by GiftNovice** [comment]
I set the three "git" param : "[unknow]"   then my code just run stop in this like the img, Is this the nccl's fault？

**Comment by GiftNovice** [comment]
![Uploading issue.jpg…]()

**Comment by GiftNovice** [comment]
![Uploading issue.jpg…]()

**Comment by GiftNovice** [comment]
![Uploading issue.jpg…]()

**Comment by daixiangzi** [comment]
Sorry, I can't see the picture you uploaded
