### ISSUE TITLE
Checkpoint for text-to-image

### ISSUE THREAD

**Issue by kl2004** [daixiangzi/VAR-CLIP#4]
Thank you for sharing the paper and the code!
They look great. Do you plan to share the checkpoint you trained, i.e.  the file `local_output/ar-ckpt-best.pth` in `demo_sample.ipynb`?

**Comment by daixiangzi** [comment]
> Thank you for sharing the paper and the code!
> They look great. Do you plan to share the checkpoint you trained, i.e. the file `local_output/ar-ckpt-best.pth` in `demo_sample.ipynb`?

Thank you for your attention. We have no plans to release weights for ckpt.pth
