### ISSUE TITLE
local_output/ar-ckpt-best.pth

### ISSUE THREAD

**Issue by Leiii-Cao** [daixiangzi/VAR-CLIP#5]
"Thank you very much for your excellent work. However, training the full model is challenging. Is there a plan to release the training checkpoints?"

**Comment by daixiangzi** [comment]
> "Thank you very much for your excellent work. However, training the full model is challenging. Is there a plan to release the training checkpoints?"

Thank you for your attention. now We have no plans to release weights for ckpt.pth.
