### ISSUE TITLE
Confusion about the VAE usage

### ISSUE THREAD

**Issue by yangbo0926** [daixiangzi/VAR-CLIP#6]
First thank you sharing this great work.
I still confuse about the usage of the VAE. 
In the demo_sample.ipynb, the VAE is built by build_vae_var func. However, during the sampling process, the VAE is not used. So what is the usage of VAE during sampling process?

**Comment by daixiangzi** [comment]
you can view here:https://github.com/daixiangzi/VAR-CLIP/blob/9047bc212578c8e12bcf9ebade5da38422a3d6a3/models/var.py#L184

**Comment by daixiangzi** [comment]
```shell
#First by sample to get idx_Bl:
idx_Bl = sample_with_top_k_top_p_(logits_BlV, rng=rng, top_k=top_k, top_p=top_p, num_samples=1)[:, :, 0]
#Then ,get  vq_feature about h_BChw by VAE:
h_BChw=self.vae_quant_proxy[0].embedding(idx_Bl) 
```

**Comment by yangbo0926** [comment]
Thank you for the response!
