### ISSUE TITLE
Training Log for VAR

### ISSUE THREAD

**Issue by Echen-Zhu** [daixiangzi/VAR-CLIP#7]
Hello, could you share your training log for VAR? I am training VAR myself, but the training loss behaves quite strangely.

**Comment by daixiangzi** [comment]
https://github.com/daixiangzi/VAR-CLIP/blob/master/logs/class_conditional_imagenet.log

**Comment by Echen-Zhu** [comment]
Thank you for your quick response !!!

**Comment by yinhengw** [comment]
> https://github.com/daixiangzi/VAR-CLIP/blob/master/logs/class_conditional_imagenet.log
Can you share the training time and GPU type?
