### ISSUE TITLE
Question about the training receipt

### ISSUE THREAD

**Issue by lxa9867** [daixiangzi/VAR-CLIP#8]
Hi Authors,

Thanks for providing this good work! I am curious about the training epoch number (1000) and want to know why the text-prompted model requires a much larger epoch number. Is this because it is more difficult to converge? May I know the FID changes during the training? Thank you!

**Comment by daixiangzi** [comment]
> Hi Authors,
> 
> Thanks for providing this good work! I am curious about the training epoch number (1000) and want to know why the text-prompted model requires a much larger epoch number. Is this because it is more difficult to converge? May I know the FID changes during the training? Thank you!


Yes, Fid is an indicator to measure the quality of image generation model, not an indicator to evaluate Text2Image. Fid should refer to var.  I think the effect of text2image  depends more on the dense text caption and image-text align

**Comment by lxa9867** [comment]
Thanks for the response
